server.port=${SERVER_PORT:8086}
server.servlet.context-path=${APP_CONTEXT_PATH:/qqauto}
server.forward-headers-strategy=framework

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://mysql8:3306/qqauto?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:zoumh}
spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER_CLASS_NAME:com.mysql.cj.jdbc.Driver}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=true
spring.jpa.show-sql=false

spring.thymeleaf.cache=true
spring.h2.console.enabled=false
