spring.application.name=qqauto
server.port=8086
server.servlet.context-path=${APP_CONTEXT_PATH:}
server.forward-headers-strategy=framework

spring.datasource.url=jdbc:h2:file:./data/qqauto;MODE=MySQL;AUTO_SERVER=TRUE
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=true
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.thymeleaf.cache=false
spring.mvc.hiddenmethod.filter.enabled=true

app.seed.admin-username=admin
app.seed.admin-password=zmh0012078070
app.seed.admin-qq=1786291497
