server.port=${SERVER_PORT:8086}
server.servlet.context-path=${APP_CONTEXT_PATH:/qqauto}
server.forward-headers-strategy=framework

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:h2:file:/app/data/qqauto;MODE=MySQL;AUTO_SERVER=TRUE}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:sa}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.h2.Driver}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=true
spring.jpa.show-sql=false

spring.thymeleaf.cache=true
spring.h2.console.enabled=false
